import os
import json
import shutil

directory = './flags/'
parent_directory = './output/'
output_directory = './output/jsons'
textures_output_directory = './output/textures'

new_filenames = []

if not os.path.exists(textures_output_directory):
    os.makedirs(textures_output_directory)

for filename in os.listdir(directory):
    file_path = os.path.join(directory, filename)

    if os.path.isfile(file_path):
        new_filename = filename.replace(" ", "_").replace("-", "_").replace("'", "").lower()
        new_file_path = os.path.join(directory, new_filename)
        os.rename(file_path, new_file_path)
        new_filenames.append(new_filename)

        shutil.copy(new_file_path, os.path.join(textures_output_directory, new_filename))

if not os.path.exists(output_directory):
    os.makedirs(output_directory)

for filename in new_filenames:
    name = os.path.splitext(filename)[0]

    json_data = {
        "credit": "Generated by Zappo Flag Generator",
        "parent": "item/flags/flag_base",
        "textures": {
            "1": f"item/flags/{name}"
        }
    }

    output_file_path = os.path.join(output_directory, f"{name}.json")

    with open(output_file_path, 'w') as json_file:
        json.dump(json_data, json_file, indent=4)

json_template = {
    "parent": "minecraft:item/generated",
    "textures": {
        "layer0": "minecraft:item/music_disc_pigstep"
    },
    "overrides": []
}

for i, filename in enumerate(new_filenames, start=1):
    name = os.path.splitext(filename)[0]
    json_template["overrides"].append({
        "predicate": {
            "custom_model_data": i
        },
        "model": f"item/flags/{name}"
    })

output_file_path = os.path.join(parent_directory, "music_disc_pigstep.json")
with open(output_file_path, 'w') as json_file:
    json.dump(json_template, json_file, indent=4)

print("JSON template with overrides for each flag has been generated and saved to the output directory.")
print("JSON files have been generated and saved to the output directory.")
print("Lowercased and modified PNGs have been copied to the output/textures directory.")
