import os
import json

directory = './flags/'
output_directory = './output/'

new_filenames = []

for filename in os.listdir(directory):
    file_path = os.path.join(directory, filename)

    if os.path.isfile(file_path):
        new_filename = filename.lower()
        new_file_path = os.path.join(directory, new_filename)
        os.rename(file_path, new_file_path)
        new_filenames.append(new_filename)

if not os.path.exists(output_directory):
    os.makedirs(output_directory)

for filename in new_filenames:
    name = os.path.splitext(filename)[0]

    json_data = {
        "credit": "Generated by Zappo Flag Generator",
        "parent": "grimurrp:flags/flag_base",
        "textures": {
            "1": f"grimurrp:models/flags/{name}"
        }
    }

    output_file_path = os.path.join(output_directory, f"{name}.json")

    with open(output_file_path, 'w') as json_file:
        json.dump(json_data, json_file, indent=4)

print("JSON files have been generated and saved to the output directory.")
